// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    options: [
      {
        name: 'comments',
        alias: 'c',
        type: Boolean,
        description: "Include sofie comments in built files."
      }
    ],
    action: function(parameters) {
      return this.printDetails();
    },
    description: "Builds routes from sophie.config file."
  };

}).call(this);
