// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    signature: String,
    options: [
      {
        name: 'comments',
        alias: 'c',
        type: Boolean,
        description: "Include sofie comments in built files."
      }
    ],
    action: function(parameters) {
      return this.printDetails();
    },
    description: "Initializes a new sophie project."
  };

}).call(this);
